### ISSUE TITLE
Automate docusaurus push with GitHub action

### ISSUE THREAD

**Issue by wyc** [spruceid/spruceid.dev#16]
Currently, this is deployed manually. It would be better to have merges to main result in gh-pages getting updated. Furthermore, we should address the issue where the domain name is overwritten for the GH pages upon push.

**Comment by bumblefudge** [comment]
Note: I figured out the domain name bit! But yes to github action deploy rather than local deploy, will get on that next week

**Comment by bumblefudge** [comment]
Finally working, no thanks to github's documentation that neither mentioned Ed25519 keys wouldn't work, nor mentioned that "passworded" keys wouldn't work.  Took hours of pointless trial, error, screensharing to other people, and googling around for other tutorials to figure out both roadblocks :(
