### ISSUE TITLE
Documentation issue in Table of Contents

### ISSUE THREAD

**Issue by wyc** [spruceid/spruceid.dev#3]
**Where are you **
https://spruceid.dev/docs/

**What's unclear or inaccurate**
It is only listing part of the website. I think it would help to list the whole website instead of having to click "DIDKit" or "Credible" to move to those subsites.

**Screenshots**
<img width="521" alt="Screen Shot 2021-01-22 at 7 58 06 AM" src="https://user-images.githubusercontent.com/858687/105493569-91b79500-5c87-11eb-9dab-039a51b51077.png">

**Additional context**
N/A

**Comment by bumblefudge** [comment]
donezo
