### ISSUE TITLE
Documentation issue in script1

### ISSUE THREAD

**Issue by wyc** [spruceid/spruceid.dev#4]
**Where are you **
https://spruceid.dev/docs/didkit/script1

**What's unclear or inaccurate**
There are aspects that should only exist within a script file and not a command line tutorial. Namely, 
- The JSON pretty-printer makes noise here but is a great feature in a script file
- "$0" references are nonsensical out of the context of a script file.

Recommend that you spend time with an author of that file to ensure this guide reads like a guide and not a deconstructed .sh. Thank you.

**Comment by bumblefudge** [comment]
time spent, deconstruction .sh guidified
