### ISSUE TITLE
index.md splashpage passover

### ISSUE THREAD

**Issue by mariavillosa** [spruceid/spruceid.dev#47]
Just want to get your thoughts on how we might be able to improve the splashpage as we move forward:

## Reappearing Table of contents

I notice that the Table of Contents has reappeared and the `hide_table_of_contents` setting has been removed. Is this intentional? 

## Referring to docs without a specific link

In https://spruceid.dev/#step-0-install-didkit we say:

>If you prefer to build manually from source or via docker, instructions are in our docs.

This text should link to the part of the docs that has the instructions, so we don't send the user on a treasure hunt.

## Remove 'fluff'?

>Once this key is on hand, you have to structure some data to be the payload of this VC you want to issue. For simplicity, let's throw this into a JSON file to be signed over in the next step. Don't worry too much about the meaning or function of any specific property if this is your first Verifiable Credential-- all things in time. You're not signing away your soul, don't worry-- these are the basic ingredients of a verified credential.
>
> code here

This is written in a fun way, but I think we're a bit repetitive in our assurances to the user. Maybe it would suffice to say:

>Once this key is on hand, you have to structure some data to be the payload of this VC you want to issue. For simplicity, let's throw this into a JSON file to be signed over in the next step. 
>
>code here
>
>(don't worry too much about the meaning or function of any specific property if this is your first Verifiable Credential - all things in time.)

? I'm not sure, this is very subjective. We might even be able to remove the caveat entirely. I'd think we want to remove as much 'fluff' as possible, but it's also nice to include a touch of personality. What do you think?

Also, with regard to fluff, maybe some of the bigger paragraphs (like the detailed could even be broken into examples (ie code or terminal sessions or something). I dread big blobs of dense text. You know that feeling where you look at a paragraph and think, 'Okay, let me take a sec to build up the nerve to tackle this text'?

But on the other hand, sometimes a direct explanation (telling instead of showing) is the only realistic way to communicate something. Let me know what you think and maybe I can help with this.

**Comment by bumblefudge** [comment]
Addressed out of band, look forward to a PR today or tomorrow!
