### ISSUE TITLE
I shouldn't be able to push to main

### ISSUE THREAD

**Issue by mariavillosa** [spruceid/spruceid.dev#52]
According to https://github.com/spruceid/process#never-push-to-the-main-branch:

>Never push to the main branch
>
>This would render peer review impossible, and the **repository security settings shouldn't even allow you to do this.**

And yet:

https://github.com/spruceid/spruceid.dev/commit/b629d0c2772d1555b88e7704fd28f5de193ba51d

Here are instructions for fixing this in the repo's settings (see the top answer): https://stackoverflow.com/questions/46146491/prevent-pushing-to-master-on-github

**Comment by bumblefudge** [comment]
now requiring approvals on main
