### ISSUE TITLE
Documentation issue in "Welcome to the Spruce Developer Portal"

### ISSUE THREAD

**Issue by wyc** [spruceid/spruceid.dev#6]
**Where are you **
https://spruceid.dev/docs/

**What's unclear or inaccurate**
We should get rid of this page and just start with DIDKit.

**Comment by wyc** [comment]
Glossary & References can be moved to the back with its own section.

**Comment by wyc** [comment]
Same with the well-written "Decentralized Identity Primer" page.

**Comment by wyc** [comment]
Please push back if this is a bad idea (and why), which it totally could be.

**Comment by bumblefudge** [comment]
what do you mean by  "the back"? Like, below the DIDKit and Credible sections in the side-nav?  I think maybe Glossary at the end, but primer stays in the intro section so there's SOMETHING there would be my thinking.

**Comment by wyc** [comment]
yeah, i guess that makes sense. no changes required
