### ISSUE TITLE
Feature request: Example HTTP shell script `example-http.sh` in DIDKit

### ISSUE THREAD

**Issue by wyc** [spruceid/spruceid.dev#8]
Please see this comment: https://github.com/spruceid/didkit/issues/8#issuecomment-766466954

**Comment by wyc** [comment]
cc @clehner

**Comment by clehner** [comment]
`example.sh` for `didkit-http` is added to `didkit` here: https://github.com/spruceid/didkit/pull/34

**Comment by bumblefudge** [comment]
This is super great, I assume we're waiting on OP to merge? LGTM!
