### ISSUE TITLE
Documentation issue in DIDKit

### ISSUE THREAD

**Issue by wyc** [spruceid/spruceid.dev#9]
We should have a single short page on "What is DIDKit?" that will answer that question to anyone who is semi-technical with architectural diagrams.

What is DIDKit?

1 paragraph

[Diagram]

1 sentence summary.

Is this a good idea?

**Comment by bumblefudge** [comment]
there's already a 1 sentence summary at the beginning of core concepts-- can we just plop the diagram and paragraph before that? I'm split between wanting one big "core concepts" file and splitting them into "what is DIDKit?" (for normals) and "core mental models" (for engineers), which would probably entail extending the latter a tiny bit.

also tell me what's in this diagram, I can't picture it.

**Comment by bumblefudge** [comment]
need to ship, tabling the extra paragraph idea for now, reopen if you want me to reconsider tomorrow
